NXBT-1305: shibboleth service provider docker image
nuxeo/nuxeo-tools-docker pull request #7
Opened 2017-12-21 14:38 UTC by funshodavid

2017-12-21 14:38 UTC, nuxeojenkins commented
[View issue in JIRA](https://jira.nuxeo.com/browse/NXBT-1305)

2017-12-21 15:26 UTC, jcarsique commented
What is the source of the copy/paste? I though that it was https://github.com/nuxeo/nuxeo-tools-docker/tree/master/openldap but the first lines of the Jenkinsfile are not consistent (cf timeout vs node)

2017-12-21 15:33 UTC, jcarsique requested changes
Please rebase compared to the current status of the source example, all previous comments to https://github.com/nuxeo/nuxeo-tools-docker/tree/master/openldap seem applicable here again

Regarding the TODO, you cannot spread the debt: it was up to @ffjdm to fix and remove the TODO or create the related JIRA tickets and reference them in the TODO. As is, you cannot copy the TODO.

2017-12-21 15:33 UTC, jcarsique commented on shibboleth-sp/Jenkinsfile
> +    node('DYNAMIC') {
wrong order (timeout vs node)

2017-12-21 15:33 UTC, jcarsique commented on shibboleth-sp/Jenkinsfile
> +            git_files_modified_for_repo = sh(returnStdout: true, script: 'git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD) | grep -c ^shibboleth-sp || true').trim()
wrong

2017-12-21 18:16 UTC, jcarsique commented
:+1: 
Can you plan with @ffjdm to replace the TODO with TODO NXBT-9999 ? Before or after merge, but soon so that the TODO don't stay as is forever.

2017-12-21 18:16 UTC, jcarsique approved these changes

2017-12-22 12:35 UTC, ffjdm approved these changes
👍

2017-12-22 14:04 UTC, merged